import 'dart:math';

import 'package:audio_video_progress_bar/audio_video_progress_bar.dart';
import 'package:favicon/favicon.dart' as Favicon;
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_linkify/flutter_linkify.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:get/get.dart';
import 'package:handles/config/config.dart';
import 'package:handles/model/models.dart';
import 'package:handles/provider/providers.dart';
import 'package:handles/screen/pages.dart';
import 'dart:io' show File, Platform;
import 'dart:math' as math;
import 'package:intl/intl.dart';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:video_thumbnail/video_thumbnail.dart';
import 'package:http/http.dart' as http;

part 'plain_chat.dart';
part 'button.dart';
part 'pro_tag.dart';
part 'subscription_banner.dart';
part 'adaptive_icon.dart';
part 'handles_status_block.dart';
part 'general_status_tag.dart';
part 'image_chat.dart';
part 'video_chat.dart';
part 'audio_chat.dart';
part 'document_chat.dart';
part 'meeting_chat.dart';
part 'service_chat.dart';